### ISSUE TITLE
Paper of fast-euclidean-clustering

### ISSUE THREAD

**Issue by jiayily** [unageek/fast-euclidean-clustering#2]
Does your implementation correspond to [FEC](https://arxiv.org/abs/2208.07678)?
But it seems your implementation is totally different from [his](https://github.com/YizhenLAO/FEC).

**Comment by unageek** [comment]
Well, when I came up with this idea, I wasn't aware of that preceding work and accidentally picked the same name for the algorithm. Anyway, the both are almost identical with subtle differences on parameters. I'm not sure if I should rename this project.

**Comment by jiayily** [comment]
@unageek Thanks. I think several projects have borrowed your idea such as https://github.com/YevgeniyEngineer/LiDAR-Processing, https://github.com/nubot-nudt/ElC-OIS.
